name: CI
on:
  workflow_dispatch:
  push:

jobs:
  list-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: list-tests-step
        name: List Tests
        run: echo "testnames=$( (cd .github/tests && find * -maxdepth 0 -type d) | jq --compact-output --slurp --raw-input 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
    outputs:
      testnames: ${{steps.list-tests-step.outputs.testnames}}

  run-test:
    needs: list-tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.list-tests.outputs.testnames) }}
    services:
      accelerator:
        image: dev.registry.tanzu.vmware.com/app-accelerator/acc-engine:latest
        credentials:
          username: robot$${{secrets.TANZUNET_ROBOT}}
          password: ${{secrets.TANZUNET_PASS}}
        ports:
          - 8888:8080


    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Wait for Engine Container
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http://localhost:8888/actuator
          timeout: 10000
      - name: ${{matrix.test}}
        run: .github/tests/run-test.sh ${{matrix.test}}
